name: Build Web

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      commit_secret: ${{secrets.commit_secret}}
      commit_email: ${{secrets.commit_email}}
      commit_name: ${{secrets.commit_name}}
      app_sentry: ${{secrets.app_sentry}}
      api_secret: ${{secrets.api_secret}}
      sentry_auth_token: ${{secrets.sentry_auth_token}}
      sentry_org: ${{secrets.sentry_org}}
      sentry_project: ${{secrets.sentry_project}}
      sentry_url: ${{secrets.sentry_url}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # TODO change to beta/stable
          #flutter-version: '1.26.0-17.2.pre'
      - name: Install Sentry
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
      - name: Setup Flutter
        run: |
          flutter doctor -v
          flutter pub get
          flutter upgrade
          flutter config --enable-web
      - name: Prepare App
        run: |
          cp lib/.env.dart.example lib/.env.dart
          cp android/app/build.gradle.prod android/app/build.gradle
          sed -i 's/secret/${{secrets.api_secret}}/g' lib/.env.dart
          echo "const FLUTTER_VERSION = const <String, String>" > lib/flutter_version.dart
          flutter --version --machine >> lib/flutter_version.dart
          echo ";" >> lib/flutter_version.dart
      - name: Build Hosted App
        run: |
          #export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} new $SENTRY_RELEASE --project ${{secrets.sentry_project}}
          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} set-commits --auto $SENTRY_RELEASE

          flutter build web --web-renderer html --release --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE --source-maps

          sed -i '/index.html/d' build/web/flutter_service_worker.js

          git config --global user.email ${{secrets.commit_email}}
          git config --global user.name ${{secrets.commit_name}}

          git clone https://${{secrets.commit_secret}}@github.com/invoiceninja/invoiceninja.git
          cd invoiceninja

          git checkout v5-develop
          cp -r ../build/web/* ./public/
          rm ./public/index.html
          git add .
          git commit -m 'New admin portal [hosted]'
          git push      
          cd ..

          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --project ${{secrets.sentry_project}} --org ${{secrets.sentry_org}} files $SENTRY_RELEASE upload-sourcemaps . --ext dart
          #cd ./build/web
          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --project ${{secrets.sentry_project}} --org ${{secrets.sentry_org}} files $SENTRY_RELEASE upload-sourcemaps . --ext map --ext js
          #cd ../..

          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} finalize $SENTRY_RELEASE
          #sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} deploys $SENTRY_RELEASE new -e production
      - name: Build Selfhosted App
        run: |
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} new $SENTRY_RELEASE --project ${{secrets.sentry_project}}
          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} set-commits --auto $SENTRY_RELEASE

          cp lib/utils/oauth.dart.foss lib/utils/oauth.dart
          cp lib/ui/app/upgrade_dialog.dart.foss lib/ui/app/upgrade_dialog.dart
          cp pubspec.foss.yaml pubspec.yaml 
          rm pubspec.lock

          flutter build web --web-renderer html --release --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE --source-maps

          git clone https://${{secrets.commit_secret}}@github.com/invoiceninja/invoiceninja.git invoiceninja_foss
          cd invoiceninja_foss
          git checkout v5-develop
          cp ../build/web/main.dart.js ./public/main.foss.dart.js
          cp ../build/web/main.dart.js.map ./public/main.foss.dart.js.map
          git add .
          git commit -m 'New admin portal [selfhosted]'
          git push
          cd ..

          mv ./build/web/main.dart.js ./build/web/main.foss.dart.js
          mv ./build/web/main.dart.js.map ./build/web/main.foss.dart.js.map

          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --project ${{secrets.sentry_project}} --org ${{secrets.sentry_org}} files $SENTRY_RELEASE upload-sourcemaps . --ext dart

          cd ./build/web
          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --project ${{secrets.sentry_project}} --org ${{secrets.sentry_org}} files $SENTRY_RELEASE upload-sourcemaps . --ext map --ext js
          cd ../..

          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} finalize $SENTRY_RELEASE
          sentry-cli --auth-token ${{secrets.sentry_auth_token}} --url ${{secrets.sentry_url}} releases --org ${{secrets.sentry_org}} deploys $SENTRY_RELEASE new -e production 